apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: my-app-container
        image: filim54595/my-app:latest  # Docker image built with tmux and node
        command: ["/bin/bash", "-c", "/app/initializeDocker.sh && tmux new-session -d -s 2 'bash -c "node index.js argss &";bash' && sleep infinity"]
        ports:
            - containerPort: 5037
              protocol: TCP
